codecov:
  max_report_age: off
  strict_yaml_branch: 7.2.x

coverage:
  round: up
  range: "80...90"
  precision: 5
  status:
    project:
      default:
        # basic
        target: 90%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        paths: 
          - "src"
       # advanced
        branches: 
          - 7.2.x
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
fixes:
  - "/home/runner/work/cas/cas/::"
